---
- name: Setup zsh environment
  hosts: localhost
  connection: local
  become: true
  become_user: "huuhait"
  tasks:
    - name: Copy dotfiles to home directory
      ansible.builtin.copy:
        src: "./{{ item }}"
        dest: "/home/huuhait"
        mode: "0775"
      with_items:
        - .config
        - .zshenv
