## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
add_newline = false

# Other languages configurations:
c.disabled = true
cmake.disabled = false
haskell.disabled = true
python.disabled = true
ruby.disabled = false
rust.disabled = false
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = false

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols
[character]
success_symbol = "[](#a6e3a1 bold)"
error_symbol = "[](#F24C00 italic)"
vicmd_symbol = "[](#f9e2af)"

[directory]
format = "[]($style)[ ](bg:#DAF0EE fg:#81A1C1)[$path](bg:#DAF0EE fg:#BBC3DF bold)[ ]($style)"
style = "bg:none fg:#DAF0EE"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:#DAF0EE fg:#A2DD9D bold)$branch](bg:#DAF0EE fg:#86AAEC)[ ]($style)"
style = "bg:none fg:#DAF0EE"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#DAF0EE fg:#b4befe)[ ]($style)"
style = "bg:none fg:#DAF0EE"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style
format = "[]($style)[[神](bg:#DAF0EE fg:#B15E6C bold)$duration](bg:#DAF0EE fg:#8499B1)[ ]($style)"
disabled = false
style = "bg:none fg:#DAF0EE"
